# Generated by Django 4.0.10 on 2023-07-04 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='保存日期')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('language', models.CharField(choices=[('CH', '中文'), ('EG', '英文')], default='', max_length=2, verbose_name='語言')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='章節課程編號')),
                ('video_url', models.URLField(blank=True, verbose_name='影片網址')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='保存日期')),
                ('classification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.classification', verbose_name='文章分類')),
            ],
        ),
    ]
